### ISSUE TITLE
Only Main Zone is exposed

### ISSUE THREAD

**Issue by sdague** [wuub/rxv#21]
I've got a 2 zone setup that I'd like to get independent control via home assistant, however there is a lot of hard coding of Main Zone in rxv code.

I'm starting to implement an approach here which is a new top level find call that returns an RXV object for each zone discovered. Will push that up once I have something working.

**Comment by wuub** [comment]
> here is a lot of hard coding of Main Zone in rxv code

True, there are a lot of hardcoded strings that have MainZone  as substring due to the fact that:
1) our receiver is single zone one
2) when we developed initial version of this lib, we (@jnnt and I) only wanted to put a nice'ish API on top of calls that we reverse engineered from sniffed traffic. But OTOH it should be pretty straightforward to parametrize them with "{zone}/...". 

>  which is a new top level find call that returns an RXV object for each zone discovered

Having separate objects to interact with do look nice from homeassistant's point of view (since you would not have to touch HA<->rxv integration). But I'm not fully convinced TBH.  A new method  returning a list of Zone objects that are API compatible also seems nice.

**Comment by sdague** [comment]
Yeh, the paramtrizing isn't bad, I hacked that up last night. How about I hack together something, throw it in a PR, and we can discuss it concretely. Probably take me a couple of days.

On October 14, 2016 9:38:42 AM EDT, Wojciech Bederski <notifications@github.com> wrote:
>> here is a lot of hard coding of Main Zone in rxv code
>
>True, there are a lot of hardcoded strings that have MainZone  as
>substring due to the fact that:
>1) our receiver is single zone one
>2) when we developed initial version of this lib, we (@jnnt and I) only
>wanted to put a nice'ish API on top of calls that we reverse engineered
>from sniffed traffic. But OTOH it should be pretty straightforward to
>parametrize them with "{zone}/...". 
>
>>  which is a new top level find call that returns an RXV object for
>each zone discovered
>
>Having separate objects to interact with do look nice from
>homeassistant's point of view (since you would not have to touch
>HA<->rxv integration). But I'm not fully convinced TBH.  A new method 
>returning a list of Zone objects that are API compatible also seems
>nice.  
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wuub/rxv/issues/21#issuecomment-253801118

-- 
Sean Dague 
http://dague.net

**Comment by wuub** [comment]
Sure thing :) 
I'm mostly concerned with backward compatibility and ease of use. As you can probably guess I'm pretty OK with hacky internals when it comes to this paticular lib :)

**Comment by sdague** [comment]
Ok work in progress patch up there. It's definitely of the quick and dirty variety. Let me know what you think about the direction.

**Comment by wuub** [comment]
Thanks to @sdague  this is now fixed in 0.2.0

Two access methods are supported
1) using `zones()` to get list of all available zones and then pick one using `.zone = "Zone Name"` 
2) using `rx.zone_controllers()` to get a complete list of `RXV` compatible objects. Each of those behaves like (almost) separate receiver :)

Thanks again to @sdague for this feature :)
