### ISSUE TITLE
MAC address or some sort of  unique ID?

### ISSUE THREAD

**Issue by mihalski** [wuub/rxv#51]
Hi,

Home Assistant is adding support for unique id's to devices and I was wondering if there are any sort of unique ID's available via the API? If not, is there a way to get the MAC address via this library?

Thank you for your work on this library. I use it daily via Home Assistant.

Regards,
Michal

**Comment by sredna** [comment]
It would be great if this could be fixed so that Home Assistant does not get confused if the receivers IP changes.

There should be plenty of information available in the ssdp reply. You have the uuid and if that is not stable (I did not test) my receiver (RX-A1030) also provides what looks to be unique values for "SerialNumber" and "UPC".
